# Import Libraries Used

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from Utilities.plot import histvstarget, distribution
from IPython.core.display import display, HTML
import sys
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
%matplotlib inline
from datetime import datetime, date
import math
import os
import cv2
import glob
import scipy.stats as st
import scipy.io as spio
import sklearn.preprocessing as skpp
import scipy.sparse.linalg as ll
from skimage.measure import block_reduce
from os.path import relpath, exists
import seaborn as sns
from PIL import Image
import time
from datetime import timedelta
from scipy.spatial.distance import cdist 
import networkx as nx
#from skimage.transform import rescale, resize, downscale_local_mean
from sklearn.utils.graph_shortest_path import graph_shortest_path
import sklearn.utils.graph_shortest_path as gspath
from sklearn.metrics.pairwise import pairwise_distances
import plotly.express as px
from scipy.stats import multivariate_normal as mvn
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
import graphviz
import pydotplus
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

import pydotplus
from IPython.display import Image  

from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd 

import warnings
warnings.filterwarnings('ignore')

# Import and preprocess the data

Remember from the data exploration notebook that we now have three different data sets now, the original, one with PCA and one with attribute selection using BFE.

First lets take 10% of the data out to be used as a validation set and create the three different training-sets from the rest.

In [2]:
#New data

In [3]:

DiabScreening_data = pd.read_csv('DiabScreening.csv')
DiabPhysExam_data = pd.read_csv('DiabPhysExam.csv')

DiabPhysExam=DiabPhysExam_data[['PtID','BldPrSys','BldPrDia','PEHeartRt','FingStkBG']]
DiabPhysExam

     PtID  BldPrSys  BldPrDia  PEHeartRt  FingStkBG
0      33     107.0      55.0        NaN        NaN
1     137      95.0      79.0        NaN        NaN
2     136      95.0      52.0       69.0        NaN
3      42     114.0      62.0       59.0        NaN
4      37      99.0      72.0       87.0        NaN
..    ...       ...       ...        ...        ...
267    68     100.0      54.0       83.0        NaN
268    61       NaN       NaN        NaN        NaN
269   161       NaN       NaN      112.0      209.0
270    53      92.0      57.0      104.0        NaN
271    78     100.0      66.0       84.0        NaN

[272 rows x 5 columns]

In [4]:
C={'Yes':1,'No':0}
DiabPhysExam['PEAbnormal']=DiabScreening_data['PEAbnormal'].map(C).fillna(DiabScreening_data['PEAbnormal'])
DiabPhysExam1 = DiabPhysExam.fillna(DiabPhysExam.mean())
#Diab1=Diab.fillna(Diab.mean())
DiabPhysExam1
DiabPhysExam2=DiabPhysExam1.fillna(0)
DiabPhysExam2

     PtID    BldPrSys   BldPrDia   PEHeartRt  FingStkBG PEAbnormal
0      33  107.000000  55.000000   93.663462    247.316          0
1     137   95.000000  79.000000   93.663462    247.316          0
2     136   95.000000  52.000000   69.000000    247.316          0
3      42  114.000000  62.000000   59.000000    247.316          0
4      37   99.000000  72.000000   87.000000    247.316          0
..    ...         ...        ...         ...        ...        ...
267    68  100.000000  54.000000   83.000000    247.316          0
268    61  101.424107  62.736607   93.663462    247.316          0
269   161  101.424107  62.736607  112.000000    209.000          0
270    53   92.000000  57.000000  104.000000    247.316          0
271    78  100.000000  66.000000   84.000000    247.316          0

[272 rows x 6 columns]

In [5]:

DiabScreening = DiabScreening_data.fillna(DiabScreening_data.mean())

DiabScreening


#DiabScreening_data

,RecID,PtID,ParentLoginVisitID,EligCritMet,ExclCritAbsent,Gender,Ethnicity,Race,DiagDt,DiagAge,...,Height,HeightUnits,HeightUnk,BldPrSys,BldPrDia,BldPrUnk,PEAbnormal,PreExistMedCond,PtCurrMed,SHNumEverB
0,57,33,141700,1,1,F,Not Hispanic or Latino,White,5/7/94 0:00,1,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,Yes,No,NaN
1,77,137,144656,1,1,M,Not Hispanic or Latino,Black/African American,5/9/95 0:00,1,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,No,No,NaN
2,62,136,142115,1,1,M,Not Hispanic or Latino,White,5/19/94 0:00,1,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,NaN,No,No
3,70,42,142675,1,1,F,Not Hispanic or Latino,White,4/5/98 0:00,4,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,No,No,NaN
4,78,37,144713,1,1,M,Not Hispanic or Latino,White,1/12/98 0:00,4,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,Yes,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,40,50,137471,1,1,M,Not Hispanic or Latino,White,3/1/96 0:00,1,...,115.200000,cm,NaN,104.000000,61.00000,32.4,No,No,No,NaN
396,41,6,137680,1,1,M,Not Hispanic or Latino,White,6/21/97 0:00,2,...,117.000000,cm,NaN,92.000000,60.00000,32.4,No,Yes,No,NaN
397,56,57,141353,1,1,F,Not Hispanic or Latino,White,7/5/98 0:00,3,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,No,Yes,NaN
398,53,19,140832,1,1,M,Not Hispanic or Latino,White,2/28/95 0:00,1,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,Yes,Yes,NaN
399,85,107,145819,1,1,M,Not Hispanic or Latino,White,9/28/96 0:00,2,...,115.782243,NaN,NaN,100.989474,66.62037,32.4,NaN,No,No,NaN

In [6]:
DiabScreening_data.columns

Index(['RecID', 'PtID', 'ParentLoginVisitID', 'EligCritMet', 'ExclCritAbsent',
       'Gender', 'Ethnicity', 'Race', 'DiagDt', 'DiagAge', 'SHMostRecent',
       'SHSeizComa', 'SHSeizComaLast12Months', 'DKAMostRecent',
       'DKANumLast12Months', 'InsModPump', 'InsModInjections', 'InsModInhaled',
       'InsModNone', 'PumpUse', 'PumpType', 'UnitsInsTotal',
       'UnitsInsBasilOrLongAct', 'NumPumpBolusOrShortAct', 'BGTestAvgNumMeter',
       'BGTestMetDatNotAvail', 'BGTestAvgNumPtRep', 'BGTestPtRepNotAvail',
       'CGMUseStat', 'CGMUseDur', 'Weight', 'WeightUnits', 'WeightUnk',
       'Height', 'HeightUnits', 'HeightUnk', 'BldPrSys', 'BldPrDia',
       'BldPrUnk', 'PEAbnormal', 'PreExistMedCond', 'PtCurrMed', 'SHNumEverB'],
      dtype='object')

In [7]:
Q={'Yes':1,'No':0, 'NaN':0}
DiabScreening_data['PreExistMedCond']=DiabScreening_data['PreExistMedCond'].map(Q).fillna(DiabScreening_data['PreExistMedCond'])
R={'Yes':1,'No':0}
DiabScreening_data['PtCurrMed']=DiabScreening_data['PtCurrMed'].map(R).fillna(DiabScreening_data['PtCurrMed'])
A={'M':1,'F':0}
DiabScreening_data['Gender']=DiabScreening_data['Gender'].map(A).fillna(DiabScreening_data['Gender'])
B={'Animas One Touch Ping':1,'Animas Vibe':2, 'Insulet OmniPod Insulin Management System':3,'Medtronic 551 (530G)':4,'Medtronic Paradigm 523 (Revel)':5,'Medtronic Paradigm 723 (Revel)':6,'MiniMed 630G':7,'Tandem t:slim':8,'Tandem t:slim X2':9,'Other':10}
DiabScreening_data['PumpType']=DiabScreening_data['PumpType'].map(B).fillna(DiabScreening_data['PumpType'])
D={'Yes':1,'No':0}
DiabScreening_data['PEAbnormal']=DiabScreening_data['PEAbnormal'].map(D).fillna(DiabScreening_data['PEAbnormal'])
E={'< 3 months ago':1,'Never':0,'3-<6 months ago':2,'1-<5 years ago':3,'5-<10 years ago':4,'6-<12 months ago':5}
DiabScreening_data['DKAMostRecent']=DiabScreening_data['DKAMostRecent'].map(E).fillna(DiabScreening_data['DKAMostRecent'])
F={'< 3 months ago':1,'Never':0,'3-<6 months ago':2,'1-<5 years ago':3,'5-<10 years ago':4,'6-<12 months ago':5}
DiabScreening_data['DKAMostRecent']=DiabScreening_data['DKAMostRecent'].map(F).fillna(DiabScreening_data['DKAMostRecent'])
G={'< 3 months ago':1,'Never':0,'3-<6 months ago':2,'1-<5 years ago':3,'5-<10 years ago':4,'6-<12 months ago':5}
DiabScreening_data['SHMostRecent']=DiabScreening_data['SHMostRecent'].map(G).fillna(DiabScreening_data['SHMostRecent'])

In [8]:
DiabScreening_data
Diab=DiabScreening_data[['PtID','PreExistMedCond','PtCurrMed','EligCritMet','ExclCritAbsent','Gender','Weight','Height','InsModPump','InsModInjections','PumpType','DiagAge','PEAbnormal','SHMostRecent',
       'SHSeizComa', 'SHSeizComaLast12Months', 'DKAMostRecent',
       'DKANumLast12Months']]
Diab

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,PumpType,DiagAge,PEAbnormal,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,8.0,1,NaN,0,0,NaN,1.0,1
1,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,7.0,1,NaN,0,0,NaN,0.0,0
2,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,5.0,1,NaN,1,1,1.0,1.0,1
3,42,0.0,0,1,1,0,NaN,NaN,1.0,NaN,1.0,4,NaN,0,0,NaN,0.0,0
4,37,1.0,0,1,1,1,NaN,NaN,1.0,NaN,1.0,4,NaN,0,0,NaN,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,50,0.0,0,1,1,1,21.7,115.2,NaN,1.0,NaN,1,0.0,0,0,NaN,0.0,0
396,6,1.0,0,1,1,1,22.3,117.0,NaN,1.0,NaN,2,0.0,0,0,NaN,3.0,0
397,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,NaN,3,NaN,0,0,NaN,0.0,0
398,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,NaN,1,NaN,5,1,1.0,4.0,0
399,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,3.0,2,NaN,3,1,0.0,3.0,0

In [9]:
Diab=Diab.fillna(Diab.mean())
Diab

#Diab=Diab[13].fillna(0, inplace=True)

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,PumpType,DiagAge,PEAbnormal,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months
0,33,1.000000,0,1,1,0,25.590654,115.782243,1.0,1.0,8.000000,1,NaN,0,0,0.692308,1.0,1
1,137,0.000000,0,1,1,1,25.590654,115.782243,1.0,1.0,7.000000,1,NaN,0,0,0.692308,0.0,0
2,136,0.184987,0,1,1,1,25.590654,115.782243,1.0,1.0,5.000000,1,NaN,1,1,1.000000,1.0,1
3,42,0.000000,0,1,1,0,25.590654,115.782243,1.0,1.0,1.000000,4,NaN,0,0,0.692308,0.0,0
4,37,1.000000,0,1,1,1,25.590654,115.782243,1.0,1.0,1.000000,4,NaN,0,0,0.692308,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,50,0.000000,0,1,1,1,21.700000,115.200000,1.0,1.0,3.288889,1,0.0,0,0,0.692308,0.0,0
396,6,1.000000,0,1,1,1,22.300000,117.000000,1.0,1.0,3.288889,2,0.0,0,0,0.692308,3.0,0
397,57,0.000000,1,1,1,0,25.590654,115.782243,1.0,1.0,3.288889,3,NaN,0,0,0.692308,0.0,0
398,19,1.000000,1,1,1,1,25.590654,115.782243,1.0,1.0,3.288889,1,NaN,5,1,1.000000,4.0,0
399,107,0.000000,0,1,1,1,25.590654,115.782243,1.0,1.0,3.000000,2,NaN,3,1,0.000000,3.0,0

In [10]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
Diab1=DiabScreening_data[['PtCurrMed','EligCritMet','ExclCritAbsent','Gender','Weight','Height','InsModPump','InsModInjections','PumpType','DiagAge','PEAbnormal','SHMostRecent',
       'SHSeizComa', 'SHSeizComaLast12Months', 'DKAMostRecent',
       'DKANumLast12Months']]
Diab1
feature_names=Diab1.columns
feature_names

Index(['PtCurrMed', 'EligCritMet', 'ExclCritAbsent', 'Gender', 'Weight',
       'Height', 'InsModPump', 'InsModInjections', 'PumpType', 'DiagAge',
       'PEAbnormal', 'SHMostRecent', 'SHSeizComa', 'SHSeizComaLast12Months',
       'DKAMostRecent', 'DKANumLast12Months'],
      dtype='object')

In [11]:
import pandas as pd
feature_names=Diab.columns
feature_names
DiabScreening_data
Diab=DiabScreening_data[['PtID','PreExistMedCond','PtCurrMed','EligCritMet','ExclCritAbsent','Gender','Weight','Height','InsModPump','InsModInjections','PumpType','DiagAge','PEAbnormal','SHMostRecent',
       'SHSeizComa', 'SHSeizComaLast12Months', 'DKAMostRecent',
       'DKANumLast12Months']]
Diab

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,PumpType,DiagAge,PEAbnormal,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,8.0,1,NaN,0,0,NaN,1.0,1
1,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,7.0,1,NaN,0,0,NaN,0.0,0
2,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,5.0,1,NaN,1,1,1.0,1.0,1
3,42,0.0,0,1,1,0,NaN,NaN,1.0,NaN,1.0,4,NaN,0,0,NaN,0.0,0
4,37,1.0,0,1,1,1,NaN,NaN,1.0,NaN,1.0,4,NaN,0,0,NaN,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,50,0.0,0,1,1,1,21.7,115.2,NaN,1.0,NaN,1,0.0,0,0,NaN,0.0,0
396,6,1.0,0,1,1,1,22.3,117.0,NaN,1.0,NaN,2,0.0,0,0,NaN,3.0,0
397,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,NaN,3,NaN,0,0,NaN,0.0,0
398,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,NaN,1,NaN,5,1,1.0,4.0,0
399,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,3.0,2,NaN,3,1,0.0,3.0,0

In [12]:
Diabetes_Data1 = pd.merge(Diab, DiabPhysExam2, how='left', left_on='PtID', right_on = 'PtID')
Diabetes_Data1

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,...,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months,BldPrSys,BldPrDia,PEHeartRt,FingStkBG,PEAbnormal_y
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
1,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
2,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
3,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
4,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,...,1,1,1.0,1.0,1,95.0,52.0,69.000000,247.316,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,0.0,0,100.0,59.0,93.663462,247.316,0
862,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0.0
863,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0
864,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0.0
865,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0

In [13]:
result = pd.merge(Diab, DiabPhysExam2, how='right', on=['PtID'])
result

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,...,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months,BldPrSys,BldPrDia,PEHeartRt,FingStkBG,PEAbnormal_y
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.000000,55.000000,93.663462,247.316,0
1,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.000000,55.000000,93.663462,247.316,0
2,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.000000,79.000000,93.663462,247.316,0
3,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.000000,79.000000,93.663462,247.316,0
4,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,...,1,1,1.0,1.0,1,95.000000,52.000000,69.000000,247.316,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,161,1.0,0,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,2.0,1,101.424107,62.736607,112.000000,209.000,0
734,53,1.0,0,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,5.0,1,92.000000,57.000000,104.000000,247.316,0
735,53,1.0,0,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,5.0,1,92.000000,57.000000,104.000000,247.316,0
736,78,0.0,0,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,5.0,1,100.000000,66.000000,84.000000,247.316,0
737,78,0.0,0,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,5.0,1,100.000000,66.000000,84.000000,247.316,0

In [16]:
Diabetes_Data = pd.merge(Diab, DiabPhysExam2, how='left', left_on='PtID', right_on = 'PtID',right_index=False)
Diabetes_Data

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,...,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months,BldPrSys,BldPrDia,PEHeartRt,FingStkBG,PEAbnormal_y
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
1,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
2,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
3,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
4,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,...,1,1,1.0,1.0,1,95.0,52.0,69.000000,247.316,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,0.0,0,100.0,59.0,93.663462,247.316,0
862,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0.0
863,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0
864,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0.0
865,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0

In [17]:
Diabetes_Data = pd.merge(Diab, DiabPhysExam2, how='left', left_on='PtID', right_on = 'PtID',right_index=True)
Diabetes_Data

,PtID_x,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,...,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months,PtID_y,BldPrSys,BldPrDia,PEHeartRt,FingStkBG,PEAbnormal_y
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,NaN,1.0,1,38,83.000000,51.000000,81.000000,160.000,0.0
1,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,NaN,0.0,0,135,95.000000,67.000000,75.000000,247.316,0
2,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,...,1,1.0,1.0,1,89,103.000000,61.000000,66.000000,247.316,0
3,42,0.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,NaN,0.0,0,70,107.000000,73.000000,85.000000,109.000,0.0
4,37,1.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,NaN,3.0,0,7,109.000000,69.000000,104.000000,267.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,50,0.0,0,1,1,1,21.7,115.2,NaN,1.0,...,0,NaN,0.0,0,23,90.000000,57.000000,86.000000,247.316,0
396,6,1.0,0,1,1,1,22.3,117.0,NaN,1.0,...,0,NaN,3.0,0,122,88.000000,64.000000,78.000000,247.316,0
397,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,...,0,NaN,0.0,0,134,100.000000,56.000000,82.000000,131.000,0
398,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,1,1.0,4.0,0,152,110.000000,68.000000,103.000000,247.316,0.0
399,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,1,0.0,3.0,0,63,101.424107,62.736607,93.663462,247.316,0

In [15]:
Diabetes_Data = pd.merge(Diab, DiabPhysExam2, left_on='PtID', how='left', right_on = 'PtID')
Diabetes_Data
#left_on='[A_c1,c2]', right_on = '[B_c1,c2]'
#patients_enc_med = pd.merge(patients_enc, medications1, how='left', left_on='pid', right_on='pid')

,PtID,PreExistMedCond,PtCurrMed,EligCritMet,ExclCritAbsent,Gender,Weight,Height,InsModPump,InsModInjections,...,SHMostRecent,SHSeizComa,SHSeizComaLast12Months,DKAMostRecent,DKANumLast12Months,BldPrSys,BldPrDia,PEHeartRt,FingStkBG,PEAbnormal_y
0,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
1,33,1.0,0,1,1,0,NaN,NaN,1.0,NaN,...,0,0,NaN,1.0,1,107.0,55.0,93.663462,247.316,0
2,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
3,137,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,0,0,NaN,0.0,0,95.0,79.0,93.663462,247.316,0
4,136,NaN,0,1,1,1,NaN,NaN,1.0,NaN,...,1,1,1.0,1.0,1,95.0,52.0,69.000000,247.316,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,57,0.0,1,1,1,0,NaN,NaN,NaN,1.0,...,0,0,NaN,0.0,0,100.0,59.0,93.663462,247.316,0
862,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0.0
863,19,1.0,1,1,1,1,NaN,NaN,NaN,1.0,...,5,1,1.0,4.0,0,112.0,70.0,93.663462,8.800,0
864,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0.0
865,107,0.0,0,1,1,1,NaN,NaN,1.0,NaN,...,3,1,0.0,3.0,0,120.0,59.0,69.000000,302.000,0

In [ ]:
Diab1=Diab.fillna(Diab.mean())
Diab1

In [ ]:
Diab1['PEAbnormal'].fillna(0, inplace=True)
Diab1

In [ ]:
Yd = Diab1['SHSeizComa']
Xd = Diab1.drop(['SHSeizComa'], axis=1)

In [ ]:
Xd_train, Xd_test, Yd_train, Yd_test = train_test_split(Xd, Yd, test_size=0.20, random_state=42)

In [ ]:
lm_logistic = LogisticRegression(random_state=0,max_iter=200)
model_logistic = lm_logistic.fit(Xd_train, Yd_train.values.ravel())
model_logistic
model_logistic.score(Xd_test, Yd_test)
pred_proba_df = pd.DataFrame(model_logistic.predict_proba(Xd_test))
threshold_list = [0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,.7,.75,.8,.85,.9,.95,.99]
for i in threshold_list:
    print ('\n******** For i = {} ******'.format(i))
    y_test_pred = np.array(pred_proba_df.iloc[:,1].apply(lambda x: 1 if x>i else 0))
    test_accuracy = metrics.accuracy_score(np.array(Yd_test), y_test_pred)
    print('Our testing accuracy is {}'.format(test_accuracy))

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, date
import math
import os
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from skmultilearn.adapt import MLkNN

In [ ]:
#Deep learning model

model_11 = Sequential()
model_11.add(Dense(12, input_dim=17, activation='relu'))
model_11.add(Dense(10, activation='relu'))
model_11.add(Dense(1, activation='sigmoid'))

model_11.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model_11.fit(Xd_train, Yd_train, epochs=30, batch_size=10)
# evaluate the keras model
_, accuracy = model_11.evaluate(Xd_test, Yd_test)
print('Accuracy: %.2f' % (accuracy*100))

In [ ]:
#Accuracy Prediction
model_11.predict(Xd_test)
prediction_11= model_11.predict(Xd_test)
prediction_11[prediction_11 < 0.1] = 0
prediction_11[prediction_11 >= 0.1] = 1

metrics.accuracy_score(prediction_11,Yd_test)


from keras.models import Sequential
from keras.layers import Dense
from keras.utils.vis_utils import plot_model
model_p = Sequential()
model_p.add(Dense(12, input_dim=10, activation='relu'))
model_p.add(Dense(10, activation='relu'))
model_p.add(Dense(1, activation='sigmoid'))
plot_model(model_p, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

In [ ]:
cm = metrics.confusion_matrix(Yd_test,prediction_11) 
fig, ax = plt.subplots(figsize=(3, 3))
ax.imshow(cm)
ax.grid(False)
ax.xaxis.set(ticks=(0, 1), ticklabels=('Predicted 0s', 'Predicted 1s'))
ax.yaxis.set(ticks=(0, 1), ticklabels=('Actual 0s', 'Actual 1s'))
ax.set_ylim(1.5, -0.5)
for i in range(2):
    for j in range(2):
        ax.text(j, i, cm[i, j], ha='center', va='center', color='red')
plt.show()

In [ ]:
#x_train, x_test, y_train, y_test
from sklearn.ensemble import RandomForestClassifier

feature_names = [f"feature {i}" for i in range(Xd.shape[1])]
forest = RandomForestClassifier(random_state=0)
forest.fit(Xd_train, Yd_train)

In [ ]:
import time
import numpy as np

start_time = time.time()
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_], axis=0)
elapsed_time = time.time() - start_time

print(f"Elapsed time to compute the importances: {elapsed_time:.3f} seconds")

In [ ]:
import pandas as pd
feature_names3=Xd.columns

forest_importances = pd.Series(importances, index=feature_names3)

fig, ax = plt.subplots()
forest_importances.plot.bar(yerr=std, ax=ax)
ax.set_title("Feature importances using MDI")
ax.set_ylabel("Mean decrease in impurity")
fig.tight_layout()

In [ ]:
feature_names3

In [ ]:
import plotly.express as px
fig1 = px.histogram(Diab1, x="Age", nbins=20,color='SHMostRecent', color_discrete_sequence=['skyblue','pink']) 
fig1.update_traces(opacity=0.8, selector=dict(type='histogram'))
fig1.update_traces(marker_line_color='rgb(0,0,0)', marker_line_width=1.5, opacity=0.6)
fig1.update_layout(autosize=True, width=500,height=400)
fig1.show()

In [ ]:
import plotly.express as px
fig1 = px.histogram(Diab1, x="DiagAge", nbins=20,color='SHMostRecent', color_discrete_sequence=['skyblue','pink']) 
fig1.update_traces(opacity=0.8, selector=dict(type='histogram'))
fig1.update_traces(marker_line_color='rgb(0,0,0)', marker_line_width=1.5, opacity=0.6)
fig1.update_layout(autosize=True, width=500,height=400)
fig1.show()

# Ensembles

In [ ]:
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
base = DecisionTreeClassifier(criterion='entropy', splitter='best', 
                                       max_depth=5, min_samples_split=2, min_samples_leaf=1, 
                                       min_weight_fraction_leaf=0.0, max_features=7, random_state=None, 
                                       max_leaf_nodes=22, min_impurity_split=1e-07, 
                                           class_weight='balanced')

model = BaggingClassifier(base_estimator=base, n_estimators=100, max_samples=1.0, max_features=1.0, 
                  bootstrap=True, bootstrap_features=False, oob_score=False, warm_start=False, 
                  n_jobs=1, random_state=None, verbose=0)
model.fit(Xd_train, Yd_train)
predictions = model.predict(Xd_test)
conf = (confusion_matrix(Yd_test,predictions))
test_accuracy = metrics.accuracy_score(np.array(Yd_test), predictions)
test_accuracy

In [ ]:
model_rf = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=5, 
                       min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                       max_features='auto', max_leaf_nodes=22, min_impurity_split=1e-07, 
                       bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, 
                       warm_start=False, class_weight='balanced')
model_rf.fit(Xd_train, Yd_train)
predictions = model.predict(Xd_test)
conf = (confusion_matrix(Yd_test,predictions))
test_accuracy_rf = metrics.accuracy_score(np.array(Yd_test), predictions)
test_accuracy_rf

The ensembles seems to provide stability and decrease the variance run to run. However they seem to introduce some bias. Looking back at when we compared entropy and gini criterion and looked at the effect of the depth and variance. Remember that the gini trees generally had few false positives while entropy trees had few false negatives. An viable hypothesis might be that the two complement each other, and because we in the ensembles above only use the one or the other. To test the hypothesis we're gonna try an VotingClassifier using the parameters search result we acquired above.

The voting classifier consists of a 5:4 ratio of entropy and gini trees since the gini trees showed less potential in the grid search. The classification is done using a majority vote rule.

In [ ]:
from sklearn.ensemble import VotingClassifier
mods = []
for i in range(1,100): # 100 Trees provides low variance.
    # A parameter combination that were sucessfull for entropy trees.
    mods.append((str(i),DecisionTreeClassifier(criterion='entropy', splitter='best', 
                               max_depth=5, min_samples_split=2, min_samples_leaf=1, 
                               min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
                               max_leaf_nodes=22, min_impurity_split=1e-07, class_weight='balanced')))
    if(i < 80):
        # A parameter combination that were sucessfull for gini trees.
        mods.append((str(i)+"gi",DecisionTreeClassifier(criterion='gini', splitter='best', 
                               max_depth=7, min_samples_split=2, min_samples_leaf=1, 
                               min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
                               max_leaf_nodes=25, min_impurity_split=1e-07, 
                                                        class_weight={0: 1.105, 1: 1.15})))
model = VotingClassifier(estimators=mods, voting='hard', n_jobs=1)
model.fit(Xd_train, Yd_train)
predictions = model.predict(Xd_test)
conf = (confusion_matrix(Yd_test,predictions))
test_accuracy1 = metrics.accuracy_score(np.array(Yd_test), predictions)
test_accuracy1

The hypothesis might be true, this is a really good separation and a AUC of nearly 89 for the validation set and 93 for the training set. Thats not a gigantic difference and hopefully the constraints on the trees have prevented the model from overfitting on the training data.

# Comparing models with K-fold cross validation using accuracy

Before giving the test set a go we train our model on the entire training dataset with some imputing. We also put it into a pipeline to automate the work-flow.

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
#missing_values='NaN'
pipeline = Pipeline([("imputer", SimpleImputer(missing_values = np.nan,
                                          strategy="mean"
                                          )),
                      ("standardizer", StandardScaler()),
                      ("VotingClassifier", model)])

In [ ]:
pipeline.fit(Xd,Yd)

In [ ]:
Xd=Xd.fillna(Xd.mean())
Xd

In [ ]:
dt_clf = DecisionTreeClassifier()
dt_clf = dt_clf.fit(Xd,Yd)
print(dt_clf)

In [ ]:
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, random_state=None, splitter='best')

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn import tree
tree.plot_tree(dt_clf)

In [ ]:
_data = tree.export_graphviz(dt_clf, out_file="None", filled=True, rounded=True,special_characters=True)

In [ ]:
import graphviz 
from graphviz import Source
_data = tree.export_graphviz(dt_clf, out_file=None)
graph = graphviz.Source(_data) 
graph.render("name of file",view = True)
import pydotplus
from IPython.display import Image

In [ ]:
import pydotplus
_data = tree.export_graphviz(dt_clf, out_file=None, filled=True, rounded=True)

graph = pydotplus.graph_from_dot_data(_data)  

Image(graph.create_png())

In [ ]:
import pydotplus
_data = tree.export_graphviz(dt_clf, out_file=None, filled=True, rounded=True,
                special_characters=True, max_depth=6)

graph = pydotplus.graph_from_dot_data(_data)  


Image(graph.create_png())

In [ ]:
# evaluate decision tree performance on train and test sets with different tree depths
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from matplotlib import pyplot

# split into train test sets
Xd_train, Xd_test, Yd_train, Yd_test = train_test_split(Xd, Yd, test_size=0.2)
# define lists to collect scores
train_scores, test_scores = list(), list()
# define the tree depths to evaluate
values = [i for i in range(1, 21)]
# evaluate a decision tree for each depth
for i in values:
	# configure the model
	model = DecisionTreeClassifier(max_depth=i)
	# fit model on the training dataset
	model.fit(Xd_train, Yd_train)
	# evaluate on the train dataset
	train_yhat = model.predict(Xd_train)
	train_acc = accuracy_score(Yd_train, train_yhat)
	train_scores.append(train_acc)
	# evaluate on the test dataset
	test_yhat = model.predict(Xd_test)
	test_acc = accuracy_score(Yd_test, test_yhat)
	test_scores.append(test_acc)
	# summarize progress
	print('>%d, train: %.3f, test: %.3f' % (i, train_acc, test_acc))
# plot of train and test scores vs tree depth
pyplot.plot(train_scores, values, '-o', label='Train')
pyplot.plot(test_scores, values, '-o', label='Test')
pyplot.legend()
pyplot.show()

In [ ]:
#CART Model
from sklearn.tree import DecisionTreeClassifier, plot_tree
DecisionTree = DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=50)
DecisionTree.fit(Xd,Yd)
plt.figure(figsize=(20,15))
plot_tree(DecisionTree)

In [ ]:
DecisionTree.fit(Xd_train, Yd_train)
Ypred=DecisionTree.predict(Xd_test)
missclf_rate= 1-metrics.accuracy_score(Yd_test, Ypred)
missclf_rate

In [ ]:
#random forest model
ntrees=[]
miss_clf_rate=[]
for i in range (1,50):
    rf=RandomForestClassifier(n_estimators=i)
    rf.fit(Xd_train, Yd_train)
    Ypred_dt=rf.predict(Xd_test)
    ntrees.append(i)
    rate=1-metrics.accuracy_score(Yd_test, Ypred)
    miss_clf_rate.append(rate)

In [ ]:
plt.figure()#(figsize=(20,10))
plt.plot(ntrees, miss_clf_rate, '-o', label='RandomForest')
plt.xlabel('Number of trees')
plt.ylabel('Missclassification rate')
plt.legend()
plt.grid()

In [ ]:
# evaluate knn performance on train and test sets with different numbers of neighbors
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot
# create dataset

# split into train test sets
#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
Xd_train, Xd_test, Yd_train, Yd_test = train_test_split(Xd, Yd, test_size=0.2, random_state=42)
# define lists to collect scores
train_scores, test_scores = list(), list()
# define the tree depths to evaluate
values = [i for i in range(1, 100)]
# evaluate a decision tree for each depth
for i in values:
	# configure the model
	model = DecisionTreeClassifier(max_depth=i)
	# fit model on the training dataset
	model.fit(Xd_train, Yd_train)
	# evaluate on the train dataset
	train_yhat = model.predict(Xd_train)
	train_acc = accuracy_score(Yd_train, train_yhat)
	train_scores.append(train_acc)
	# evaluate on the test dataset
	test_yhat = model.predict(Xd_test)
	test_acc = accuracy_score(Yd_test, test_yhat)
	test_scores.append(test_acc)
	# summarize progress
	print('>%d, train: %.3f, test: %.3f' % (i, train_acc, test_acc))
# plot of train and test scores vs number of neighbors
pyplot.plot(values, train_scores, '-o', label='Train')
pyplot.plot(values, test_scores, '-o', label='Test')
pyplot.legend()
pyplot.show()

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from matplotlib.legend_handler import HandlerLine2D

train_results = []
test_results = []
trees = [5, 10, 15, 30, 45, 60, 80, 100]

for nb_trees in trees:
    rf = RandomForestClassifier(n_estimators=nb_trees)
    rf.fit(Xd_train, Yd_train)

    train_results.append(mean_squared_error(Yd_train, rf.predict(Xd_train)))
    test_results.append(mean_squared_error(Yd_test, rf.predict(Xd_test)))

line1, = plt.plot(trees, train_results, color="r", label="Training Score")
line2, = plt.plot(trees, test_results, color="g", label="Testing Score")

plt.legend(handler_map={line1: HandlerLine2D(numpoints=2)})
plt.ylabel('MSE')
plt.xlabel('list_nb_trees')
plt.show()

In [ ]:
#SVM Model
# fit the model
from sklearn.svm import OneClassSVM
import numpy as np
import pylab as pl
import matplotlib.font_manager
from sklearn import svm
rate_svm=[]
rate_rf_auc=[]
for i in range (1,100):
    clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.1)
    clf.fit(Xd_train,Yd_train)
    y_pred_train = clf.predict(Xd_train)
    y_pred_test = clf.predict(Xd_test)
    #y_pred_outliers = clf.predict(X_outliers)
    n_error_train = y_pred_train[y_pred_train == -1].size
    n_error_test = y_pred_test[y_pred_test == -1].size
    SVM_rate = 1-metrics.accuracy_score(Yd_test, y_pred_test)
    SVM_rate
    rate_svm.append(SVM_rate)
  #  pyplot.plot(rate_svm, gamma, '-o', label='Train')
#n_error_outliers = y_pred_outliers[y_pred_outliers == 1].size

In [ ]:
SVM_rate

Diab

In [ ]:
# Dataset with PCA
import Utilities.mypca as PCA
pca = PCA.MyPCA()
pca.fit(Xd_train)
PCA_x_train = pca.fit_transform(5, Xd_train)
PCA_x_val = pca.fit_transform(5, Xd_test)
print(PCA_x_train.shape)

In [ ]:
Xd_train, Xd_test, Yd_train, Yd_test = train_test_split(Xd, Yd, test_size=0.20, random_state=42)

In [ ]:
Xd_test.shape

In [ ]:
Xd_train.shape

In [ ]:
Yd_train.shape

In [ ]:
mean_x_train = np.mean(Xd_train)
std_x_train = np.std(Xd_train)
std = lambda Xd: ((Xd - mean_x_train)/std_x_train)
inv_std = lambda Xd: ((Xd*std_x_train + mean_x_train))
x_train_std1 = std(Xd_train)
x_test_std1 = std(Xd_test)

In [ ]:
x_train_std1

In [ ]:
x_test_std1

In [ ]:
Diab2=DiabScreening_data[['PtID','PreExistMedCond','PtCurrMed','EligCritMet','ExclCritAbsent','Gender','Weight','Height','InsModPump','InsModInjections','PumpType','DiagAge','PEAbnormal','SHMostRecent',
       'SHSeizComa', 'SHSeizComaLast12Months', 'DKAMostRecent',
       'DKANumLast12Months']]
Diab2

In [ ]:
cols1=Diab2.columns
cols1

In [ ]:
trainingdata1 = pd.DataFrame(np.hstack((x_train_std1, Yd_train[:,np.newaxis])), columns = cols1)
validationdata1 = pd.DataFrame(np.hstack((x_test_std1, Yd_test[:,np.newaxis])), columns = cols1)
trainingdata1.head()

In [ ]:
BFE_cols1 = ['PtID', 'PreExistMedCond', 'PtCurrMed', 'EligCritMet', 'ExclCritAbsent',
       'Gender', 'Weight', 'Height', 'InsModPump', 'InsModInjections',
       'PumpType', 'DiagAge', 'PEAbnormal', 'SHMostRecent',
       'SHSeizComaLast12Months', 'DKAMostRecent', 'DKANumLast12Months']
BFE_x_train1 = Diab[BFE_cols1]
BFE_x_val1 = validationdata1[BFE_cols1]
print(BFE_x_train1.shape)

In [ ]:
BFE_x_train1

In [ ]:
BFE_x_train1=BFE_x_train1.fillna(BFE_x_train1.mean())
BFE_x_train1

BFE_x_train1['PEAbnormal'] = BFE_x_train1['PEAbnormal'].fillna(0)
BFE_x_train1

In [ ]:
from sklearn.svm import SVC
LR = LogisticRegression()
GB = GaussianNB() # Gaussian NB since we have continous data.
KN = KNeighborsClassifier(n_neighbors=4, p = 2) # 4 Neighbors by euclidian distance.
DT_GINI = DecisionTreeClassifier(criterion="gini",max_depth=4) # Decision Tree with Gini impurity for quality of split
DT_IG = DecisionTreeClassifier(criterion="entropy",max_depth=4) # Information gain for quality of split
SV = SVC() # Support vector machine classifier.

modelnames = ["Logistic regression","Gaussian Naive Bayes", "4-Neighbors","Decisiontree Gini",
              "Decisiontree Information gain", "Support vector machine"]

models = zip(modelnames,[LR, GB, KN, DT_GINI, DT_IG, SV])
results_PCA = []
results_BFE = []
results = []

for name,model in models:
    kfold = KFold(n_splits=18)
    #cv_result_PCA = cross_val_score(model, PCA_x_train, y_train, cv = kfold,scoring = "accuracy")
    cv_result_BFE = cross_val_score(model, BFE_x_train1, Yd, cv = kfold,scoring = "accuracy")
   # cv_result_BFE = cross_val_score(model, Xd_train, Yd_train, cv = kfold,scoring = "accuracy")
    cv_result = cross_val_score(model, Xd_train, Yd_train, cv = kfold,scoring = "accuracy")
   # results_PCA.append(cv_result_PCA)
    results_BFE.append(cv_result_BFE)
    results.append(cv_result)

print("PCA")
for name, res in zip(modelnames, results_PCA):
    print(name,res.mean())
print()
print("BFE")
for name, res in zip(modelnames, results_BFE):
    print(name,res.mean())
print()
print("All Data")
for name, res in zip(modelnames, results):
    print(name,res.mean())

In [ ]:
f, ax = plt.subplots(figsize=(15,10))

plt.subplot(3, 1, 2)
ax = sns.boxplot(data=results_BFE)
ax.set_title("BFE")
ax.set_xticklabels(modelnames)

plt.subplot(3, 1, 3)
ax = sns.boxplot(data=results)
ax.set_xticklabels(modelnames)
ax.set_title("Raw data")